name: 'Dependency Review'

on: 
  push:
    paths:
      - "package.json"

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v3
      with:
        fetch-depth: 2 # checkout this revision and the prior one

    - name: Dependency Review
      uses: actions/dependency-review-action@v3
      with:
        base-ref: refs/heads/master~1
        head-ref: refs/heads/master
