on: [push] 
 
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    name: dependency review
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          base-ref: refs/heads/master~1
          head-ref: refs/heads/master
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports

  njsscan:
    runs-on: ubuntu-latest
    name: njsscan check
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '.'
